version: "3.8"
services:
  database:
    container_name: quotes-database
    build:
      context: ./database
    ports:
      - 5432:5432
    env_file:
      - ./env/database.env
    networks:
      - quotes-app-network
  backend:
    container_name: quotes-backend
    build:
      context: ./backend
    ports:
      - 8080:8080
    env_file:
      - ./env/backend.env
    depends_on:
      - database
    networks:
      - quotes-app-network
    stdin_open: true
    tty: true
  frontend:
    container_name: quotes-frontend
    build:
      context: ./frontend
    ports:
      - 80:80
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - quotes-app-network

networks:
  quotes-app-network:
