version: "3.8"
services:
  database:
    container_name: quotes-app-database
    image: postgres:latest
    volumes:
      - ./database/dump.sqlv:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    env_file:
      - ./env/database.env
  backend:
    container_name: todo-backend-app
    build:
      context: ./backend
     #dockerfile: Dockerfile.dev
    volumes:
      - ./backend/src:/app/src
    ports:
      - 8000:8000
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    container_name: todo-frontend-app
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mongodbdata:
